### ISSUE TITLE
Revert back to local building

### ISSUE THREAD

**Issue by mariusrueve** [ciw-project-2023/coaler#13]
When installing like shown in the README, installing won't work, because the hash is not found (different hashing on my system needed)

I built locally, deleted `conan.lock` and changed `conan.py` to: 

```
    def requirements(self):
        self.requires("rdkit/0.0.1")
        self.requires("boost/1.83.0")
        self.requires("catch2/2.13.10")
        self.requires("spdlog/1.12.0")
```

Maybe docu of building in RDKit README (?)

**Comment by HokageM** [comment]
I have the same problem with ubuntu 22

"rdkit/0.0.1@ciw/294b74786074affd9160dec93fd8dc41"  is not found

**Comment by mariusrueve** [comment]
I can create documentation in rdkit fork for local installations, not using remotes. I think this fixed my problems (and changing conan.lock etc manually)
