### ISSUE TITLE
Embedding Error when input molecule matches core

### ISSUE THREAD

**Issue by MSchokolowski** [ciw-project-2023/coaler#67]
The embedder throws an error when a molecule in the input file matches the core perfectly.
For the time being only use data without this issue (e.g. AID_5 has this problem)

**Comment by cnoahris** [comment]
For clarification: This occurs when one of the input molecules is equal to the shared core i.e. mol = core

**Comment by HokageM** [comment]
Works for AID_5.smi and examples like:

c1ccccc1
c1ccccc1O
c1ccccc1S

**Comment by mariusrueve** [comment]
Same for
```
c1ccc(cc(O)cc2)c2c1
c1ccc(cc(OC)cc2)c2c1
c1ccc(cc(OCCC)cc2)c2c1
c1ccc(cc(OCCCC)cc2)c2c1
```
