### ISSUE TITLE
remove potential duplicate starting assemblies

### ISSUE THREAD

**Issue by cnoahris** [ciw-project-2023/coaler#76]

**Comment by MSchokolowski** [comment]
Habe ich schon auf dem branch fix-mol-is-core-issue, muss das noch testen und dann gehts schon in den PR. Eig will ich da auch noch das eigentliche Problem fixen aber das kann ich immernoch nach dem PR

**Comment by HokageM** [comment]
- Use UniquePoseId as Hash for Pose
- Only add starting essembly if unique Pose for Mol
